insert into phone (name, attributes_id, brand, points_id) values ('Aerified', 1, 'Westwood Holdings Group Inc', null);
insert into phone (name, attributes_id, brand, points_id) values ('Zaam-Dox', 2, 'CoreLogic, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Veribet', 3, 'Hospitality Properties Trust', null);
insert into phone (name, attributes_id, brand, points_id) values ('Overhold', 4, 'Apollo Commercial Real Estate Finance', null);
insert into phone (name, attributes_id, brand, points_id) values ('Tresom', 5, 'James Hardie Industries plc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Trippledex', 6, 'Global Indemnity Limited', null);
insert into phone (name, attributes_id, brand, points_id) values ('Y-Solowarm', 7, 'Navigant Consulting, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Pannier', 8, 'Universal Display Corporation', null);
insert into phone (name, attributes_id, brand, points_id) values ('Hatity', 9, 'Bank of N.T. Butterfield & Son Limited (The)', null);
insert into phone (name, attributes_id, brand, points_id) values ('Veribet', 10, 'Workhorse Group, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Zamit', 11, 'CalAtlantic Group, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Overhold', 12, 'SecureWorks Corp.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Treeflex', 13, 'Achillion Pharmaceuticals, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Konklab', 14, 'Dupont Fabros Technology, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Asoka', 15, 'Mohawk Industries, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Tin', 16, 'Turtle Beach Corporation', null);
insert into phone (name, attributes_id, brand, points_id) values ('Bamity', 17, 'Medtronic plc', null);
insert into phone (name, attributes_id, brand, points_id) values ('Tempsoft', 18, 'Plexus Corp.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Otcom', 19, 'On Deck Capital, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Zaam-Dox', 20, 'Ferro Corporation', null);
insert into phone (name, attributes_id, brand, points_id) values ('Stringtough', 21, 'Air Lease Corporation', null);
insert into phone (name, attributes_id, brand, points_id) values ('Toughjoyfax', 22, 'Eaton Vance Short Diversified Income Fund', null);
insert into phone (name, attributes_id, brand, points_id) values ('Trippledex', 23, 'B&G Foods, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Fintone', 24, 'J. Jill, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Tresom', 25, 'ASA Gold and Precious Metals Limited', null);
insert into phone (name, attributes_id, brand, points_id) values ('Viva', 26, 'Omega Healthcare Investors, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Greenlam', 27, 'Novadaq Technologies Inc', null);
insert into phone (name, attributes_id, brand, points_id) values ('Pannier', 28, 'Church & Dwight Company, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Viva', 29, 'Amplify Online Retail ETF', null);
insert into phone (name, attributes_id, brand, points_id) values ('Tres-Zap', 30, 'Rogers Communication, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Konklab', 31, 'Global X Internet of Things ETF', null);
insert into phone (name, attributes_id, brand, points_id) values ('Sonair', 32, 'Bio-Rad Laboratories, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Flowdesk', 33, 'PhotoMedex, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Zamit', 34, 'Pioneer Power Solutions, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Rank', 35, 'Arista Networks, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Ronstring', 36, 'Select Bancorp, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Zontrax', 37, 'Ra Pharmaceuticals, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Fix San', 38, 'Global Indemnity Limited', null);
insert into phone (name, attributes_id, brand, points_id) values ('Aerified', 39, 'Sears Holdings Corporation', null);
insert into phone (name, attributes_id, brand, points_id) values ('Flowdesk', 40, 'Amphenol Corporation', null);
insert into phone (name, attributes_id, brand, points_id) values ('Bitwolf', 41, 'XTL Biopharmaceuticals Ltd.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Matsoft', 42, 'Nustar GP Holdings, LLC', null);
insert into phone (name, attributes_id, brand, points_id) values ('Rank', 43, 'Crown Crafts, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Otcom', 44, 'Allegion plc', null);
insert into phone (name, attributes_id, brand, points_id) values ('Domainer', 45, 'M III Acquisition Corp.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Solarbreeze', 46, 'Meritage Corporation', null);
insert into phone (name, attributes_id, brand, points_id) values ('Tresom', 47, 'Protective Life Corporation', null);
insert into phone (name, attributes_id, brand, points_id) values ('Daltfresh', 48, 'First Trust Indxx Global Natural Resources Income ETF', null);
insert into phone (name, attributes_id, brand, points_id) values ('Domainer', 49, 'Blackrock MuniYield Quality Fund II, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Job', 50, 'Washington Prime Group Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Zamit', 51, 'Pacific Drilling S.A.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Pannier', 52, 'DTE Energy Company', null);
insert into phone (name, attributes_id, brand, points_id) values ('Lotstring', 53, 'CDW Corporation', null);
insert into phone (name, attributes_id, brand, points_id) values ('Voltsillam', 54, 'Golden Ocean Group Limited', null);
insert into phone (name, attributes_id, brand, points_id) values ('Voyatouch', 55, 'First Interstate BancSystem, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Asoka', 56, 'Global X Millennials Thematic ETF', null);
insert into phone (name, attributes_id, brand, points_id) values ('Opela', 57, 'MainStay DefinedTerm Municipal Opportunities Fund', null);
insert into phone (name, attributes_id, brand, points_id) values ('Alphazap', 58, 'Great Ajax Corp.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Kanlam', 59, 'Vascular Biogenics Ltd.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Stringtough', 60, 'Fidus Investment Corporation', null);
insert into phone (name, attributes_id, brand, points_id) values ('Opela', 61, 'First Trust Strategic Income ETF', null);
insert into phone (name, attributes_id, brand, points_id) values ('Voyatouch', 62, 'MRC Global Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Ronstring', 63, 'Selective Insurance Group, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Treeflex', 64, 'Mexico Fund, Inc. (The)', null);
insert into phone (name, attributes_id, brand, points_id) values ('Greenlam', 65, 'Zosano Pharma Corporation', null);
insert into phone (name, attributes_id, brand, points_id) values ('Daltfresh', 66, 'Cleveland BioLabs, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Cardguard', 67, 'FIRST REPUBLIC BANK', null);
insert into phone (name, attributes_id, brand, points_id) values ('Bitwolf', 68, 'Nuveen Diversified Dividend and Income Fund', null);
insert into phone (name, attributes_id, brand, points_id) values ('Sonsing', 69, 'Telephone and Data Systems, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Opela', 70, 'Zhaopin Limited', null);
insert into phone (name, attributes_id, brand, points_id) values ('Latlux', 71, 'BSB Bancorp, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Duobam', 72, 'Allete, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Latlux', 73, 'Eastern Company (The)', null);
insert into phone (name, attributes_id, brand, points_id) values ('Kanlam', 74, 'AmTrust Financial Services, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Fixflex', 75, 'Geopark Ltd', null);
insert into phone (name, attributes_id, brand, points_id) values ('Cardguard', 76, 'Quest Diagnostics Incorporated', null);
insert into phone (name, attributes_id, brand, points_id) values ('Temp', 77, 'MFA Financial, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Fix San', 78, 'Cellular Biomedicine Group, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Y-find', 79, 'Qwest Corporation', null);
insert into phone (name, attributes_id, brand, points_id) values ('Cardify', 80, 'PowerShares S&P SmallCap Industrials Portfolio', null);
insert into phone (name, attributes_id, brand, points_id) values ('Matsoft', 81, 'Clovis Oncology, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Cardify', 82, 'Microbot Medical Inc. ', null);
insert into phone (name, attributes_id, brand, points_id) values ('Redhold', 83, 'Washington Federal, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Latlux', 84, 'Valley National Bancorp', null);
insert into phone (name, attributes_id, brand, points_id) values ('Biodex', 85, 'Match Group, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Tin', 86, 'Smith (A.O.) Corporation', null);
insert into phone (name, attributes_id, brand, points_id) values ('Wrapsafe', 87, 'Unilever PLC', null);
insert into phone (name, attributes_id, brand, points_id) values ('Hatity', 88, 'Earthstone Energy, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Solarbreeze', 89, 'TechnipFMC plc', null);
insert into phone (name, attributes_id, brand, points_id) values ('Regrant', 90, 'Sabra Healthcare REIT, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Sonsing', 91, 'Yahoo! Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Greenlam', 92, 'Omega Healthcare Investors, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Konklab', 93, 'Hornbeck Offshore Services', null);
insert into phone (name, attributes_id, brand, points_id) values ('Gembucket', 94, 'JMP Group LLC', null);
insert into phone (name, attributes_id, brand, points_id) values ('Ronstring', 95, 'AMREP Corporation', null);
insert into phone (name, attributes_id, brand, points_id) values ('Quo Lux', 96, 'AptarGroup, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Tresom', 97, 'Navigator Holdings Ltd.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Opela', 98, 'Smith & Nephew SNATS, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Andalax', 99, 'Blackhawk Network Holdings, Inc.', null);
insert into phone (name, attributes_id, brand, points_id) values ('Mat Lam Tam', 100, 'USLIFE Income Fund, Inc.', null);
