insert into phone (name, attributes_id, brand, points_id, votes) values ('Opela', 1, 'Home Bancorp, Inc.', null, 4);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Cardguard', 2, 'XG Technology, Inc', null, 41);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Zaam-Dox', 3, 'FutureFuel Corp.', null, 71);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Namfix', 4, 'Hoegh LNG Partners LP', null, 67);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Cardify', 5, 'Xilinx, Inc.', null, 92);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Span', 6, 'QAD Inc.', null, 3);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Zaam-Dox', 7, 'CPI Card Group Inc.', null, 57);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Viva', 8, 'Global X Social Media ETF', null, 98);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Bamity', 9, 'Murphy Oil Corporation', null, 83);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Namfix', 10, 'Iamgold Corporation', null, 72);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Fintone', 11, 'Pebblebrook Hotel Trust', null, 59);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Konklux', 12, 'Toll Brothers Inc.', null, 94);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Keylex', 13, 'Envision Healthcare Corporation', null, 93);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Asoka', 14, 'First Community Financial Partners, Inc.', null, 34);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Bitwolf', 15, 'Nautilus Group, Inc. (The)', null, 48);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Subin', 16, 'Landmark Infrastructure Partners LP', null, 57);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Asoka', 17, 'Internet Initiative Japan, Inc.', null, 94);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Y-find', 18, 'Ambev S.A.', null, 6);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Greenlam', 19, 'ONE Gas, Inc.', null, 92);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Viva', 20, 'Marine Products Corporation', null, 25);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Zamit', 21, 'National Energy Services Reunited Corp.', null, 33);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Konklab', 22, 'PNC Financial Services Group, Inc. (The)', null, 41);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Zoolab', 23, 'National General Holdings Corp', null, 84);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Viva', 24, 'Welltower Inc.', null, 32);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Keylex', 25, 'Bank of America Corporation', null, 40);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Sonair', 26, 'The Charles Schwab Corporation', null, 58);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Fixflex', 27, 'Guidewire Software, Inc.', null, 25);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Konklab', 28, 'ZAGG Inc', null, 1);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Otcom', 29, 'Tsakos Energy Navigation Ltd', null, 93);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Konklab', 30, 'RELX N.V.', null, 14);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Duobam', 31, 'Access National Corporation', null, 62);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Fixflex', 32, 'Versum Materials, Inc.', null, 32);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Zontrax', 33, 'Argo Group International Holdings, Ltd.', null, 9);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Tin', 34, 'KAR Auction Services, Inc', null, 15);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Tampflex', 35, 'Gaia, Inc.', null, 43);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Flowdesk', 36, 'Ulta Beauty, Inc.', null, 2);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Wrapsafe', 37, 'Novartis AG', null, 6);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Voltsillam', 38, 'AquaBounty Technologies, Inc.', null, 98);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Bytecard', 39, 'Landauer, Inc.', null, 89);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Daltfresh', 40, 'iPath US Treasury Flattener ETN', null, 97);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Redhold', 41, 'Horizon Technology Finance Corporation', null, 33);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Subin', 42, 'Omega Flex, Inc.', null, 11);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Lotlux', 43, 'Fuwei Films (Holdings) Co., Ltd.', null, 36);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Y-find', 44, 'Charter Financial Corp.', null, 16);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Bitchip', 45, 'Enstar Group Limited', null, 97);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Sonair', 46, 'LG Display Co., Ltd.', null, 4);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Duobam', 47, 'Heidrick & Struggles International, Inc.', null, 31);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Konklab', 48, 'Tuttle Tactical Management U.S. Core ETF', null, 21);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Ronstring', 49, 'China Eastern Airlines Corporation Ltd.', null, 22);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Matsoft', 50, 'Blackrock Enhanced Government Fund, Inc', null, 87);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Biodex', 51, 'Advent/Claymore Enhanced Growth & Income Fund', null, 40);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Gembucket', 52, 'Drive Shack Inc.', null, 44);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Lotlux', 53, 'Novogen Limited', null, 23);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Opela', 54, 'Nuveen Insured New York Select Tax-Free Income Portfolio', null, 47);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Toughjoyfax', 55, 'Lam Research Corporation', null, 79);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Job', 56, 'Continental Building Products, Inc.', null, 70);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Temp', 57, 'PetMed Express, Inc.', null, 36);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Tres-Zap', 58, 'Motorcar Parts of America, Inc.', null, 34);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Lotlux', 59, 'Everspin Technologies, Inc.', null, 48);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Asoka', 60, 'Dover Downs Gaming & Entertainment Inc', null, 3);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Bigtax', 61, 'Fabrinet', null, 61);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Lotlux', 62, 'Prudential Financial, Inc.', null, 22);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Otcom', 63, 'Hanwha Q CELLS Co., Ltd. ', null, 18);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Konklux', 64, 'Veritone, Inc.', null, 76);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Otcom', 65, 'Bassett Furniture Industries, Incorporated', null, 9);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Aerified', 66, 'Patterson-UTI Energy, Inc.', null, 43);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Bitchip', 67, 'MaxPoint Interactive, Inc.', null, 61);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Andalax', 68, 'Amtech Systems, Inc.', null, 54);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Aerified', 69, 'Cullen/Frost Bankers, Inc.', null, 19);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Zamit', 70, 'BB&T Corporation', null, 80);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Prodder', 71, 'Blackrock MuniEnhanced Fund, Inc.', null, 92);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Andalax', 72, 'Royce Value Trust, Inc.', null, 51);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Gembucket', 73, 'Entergy Arkansas, Inc.', null, 87);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Span', 74, 'Omeros Corporation', null, 64);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Fix San', 75, 'Armstrong Flooring, Inc.', null, 50);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Zaam-Dox', 76, 'BGC Partners, Inc.', null, 42);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Cardify', 77, 'Tandy Leather Factory, Inc.', null, 32);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Alpha', 78, 'Del Frisco''s Restaurant Group, Inc.', null, 28);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Toughjoyfax', 79, 'Barnes & Noble, Inc.', null, 16);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Tampflex', 80, 'First Trust International Multi-Asset Diversified Income Index', null, 72);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Bigtax', 81, 'John Hancock Tax Advantaged Dividend Income Fund', null, 84);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Stim', 82, 'Alpine Global Premier Properties Fund', null, 75);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Ronstring', 83, 'FelCor Lodging Trust Incorporated', null, 76);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Tresom', 84, 'Urstadt Biddle Properties Inc.', null, 3);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Bytecard', 85, 'Eaton Vance Tax-Managed Buy-Write Income Fund', null, 46);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Regrant', 86, 'Clearwater Paper Corporation', null, 99);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Viva', 87, 'Apollo Tactical Income Fund Inc.', null, 96);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Sub-Ex', 88, 'Pacific American Income Shares, Inc.', null, 86);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Ronstring', 89, 'Aflac Incorporated', null, 4);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Cardguard', 90, 'Sysco Corporation', null, 78);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Tampflex', 91, 'Heidrick & Struggles International, Inc.', null, 26);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Quo Lux', 92, 'Royce Global Value Trust, Inc.', null, 67);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Toughjoyfax', 93, 'TG Therapeutics, Inc.', null, 65);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Tempsoft', 94, 'Netflix, Inc.', null, 93);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Home Ing', 95, 'Hawaiian Electric Industries, Inc.', null, 50);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Subin', 96, 'TAT Technologies Ltd.', null, 47);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Fintone', 97, 'VelocityShares Daily 2x VIX Medium-Term ETN', null, 87);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Bitwolf', 98, 'Orion Group Holdings, Inc.', null, 2);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Holdlamis', 99, 'Tennessee Valley Authority', null, 100);
insert into phone (name, attributes_id, brand, points_id, votes) values ('Gembucket', 100, 'ProPhase Labs, Inc.', null, 7);
